### ISSUE TITLE
Theme keeps resetting

### ISSUE THREAD

**Issue by uaktags** [Skitals/unraid-theme-engine#1]
I keep setting the theme to something like BrushThreeDark-Black. I also ensure that ThemeEngine is enabled. However every few moments it appears that the settings get fubar'd and reset. 
![Screenshot_2020-02-24_11-45-15](https://user-images.githubusercontent.com/893684/75172440-443f4a80-56fb-11ea-9fda-2a0e5633453d.png)

![Screenshot_2020-02-24_11-45-39](https://user-images.githubusercontent.com/893684/75172448-486b6800-56fb-11ea-8ed8-ae08e9f208bd.png)

**Comment by Skitals** [comment]
What version of unraid? I think the 6.8.X broke something. I'm still on a 6.8 RC so I haven't tested yet.

**Comment by uaktags** [comment]
6.8.2

I'll downgrade to try another 6.8.x

**Comment by Skitals** [comment]
> 6.8.2
> 
> I'll downgrade to try another 6.8.x

I'm not sure exactly when they made the change, probably 6.8 final. They made some changes to better support custom themes which ironically seems to have broken this plugin ;)

**Comment by uaktags** [comment]
Currently testing right now, but this may just be a conflict between "day-and-night" plugin that I just noticed I had and the theme.engine which would make perfect sense.

**Comment by uaktags** [comment]
So yea, it was the day-and-night plugin causing issues. Otherwise the theme-engine appears to be working on 6.8.2

**Comment by Skitals** [comment]
> So yea, it was the day-and-night plugin causing issues. Otherwise the theme-engine appears to be working on 6.8.2

Thanks for the update. I looked at the changes in the latest webgui and didn't see anything that should of broken anything, thank you for confirming. I still don't have a machine running 6.8 stable as I'm waiting for a new build with 5.x kernel (6.9 rc series).
